name: budoux_dart
description: A BudouX implementation in Dart.
version: 1.1.0
repository: https://github.com/KoheiKanagu/budoux-dart

environment:
  sdk: ^3.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
