name: budoux_dart
description: A BudouX implementation in Dart.
version: 1.0.0
repository: https://github.com/KoheiKanagu/budoux-dart

environment:
  sdk: ^3.1.2

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
